repos:
  - repo: local
    hooks:
      - id: system
        name: isort
        args: ["--profile", "black"]
        entry: poetry run isort .
        pass_filenames: false
        language: system
      - id: system
        name: Black
        entry: poetry run black .
        pass_filenames: false
        language: system
      - id: system
        name: autoflake
        entry: poetry run autoflake -r --in-place --remove-unused-variables .
        pass_filenames: false
        language: system
      - id: system
        name: pytest
        entry: poetry run pytest -n auto
        pass_filenames: false
        language: system
      - id: system
        name: generate docs
        entry: poetry run gen-all
        pass_filenames: false
        language: system