site_name: PyETR

nav:
  - 'Home': 'index.md'
  - 'Getting started':
    - 'Overview' : 'getting_started/overview.md'
    - 'Installation': 'getting_started/installation.md'
    - 'Python': 'getting_started/python.md'
  - 'Usage':
    - 'First Steps': 'usage/first_steps.md'
    - 'Pre-defined Cases': 'usage/pre_defined_cases.md'
    - 'View Construction': 'usage/view_construction.md'
    - 'View Methods Example': 'usage/view_methods_example.md'
    - 'Direct Decision Example': 'usage/direct_decision_example.md'
  - 'Advanced Usage':
    - 'Overview': 'advanced_usage/overview.md'
    - 'Defining Inference': 'advanced_usage/defining_inference.md'
    - 'Func Callers': 'advanced_usage/func_callers.md'
    - 'Troubleshooting': 'advanced_usage/troubleshooting.md'
    - 'Equality': 'advanced_usage/view_equality_and_equivalence.md'
  - 'Theory' :
    - 'Systems from R&I' : 'theory/systems.md'
    - 'Differences with R&I' : 'theory/differences.md'
  - 'Reference':
    - 'Overview': 'reference/overview.md'
    - 'Case Index': 'reference/case_index.md'
    - 'View Methods': 'reference/view_methods.md'
    - 'Inference Index': 'reference/inference_index.md'
  - 'Glossary' : 'glossary.md'
  - 'For Developers': 'development.md'
  - 'Credits': 'credits.md'
theme:
  name: 'material'
  features:
    - content.code.copy
    - navigation.footer
  palette:
    - scheme: default
      primary: 'black'
      accent: 'amber'
      toggle:
          icon: material/lightbulb
          name: Switch to dark mode
    - scheme: slate
      primary: 'yellow'
      accent: 'amber'
      toggle:
          icon: material/lightbulb-outline
          name: Switch to light mode
  icon:
    logo: fontawesome/solid/brain

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - toc:
      permalink: true
  - attr_list
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search:
      separator: '[\s\-\.\_]+'