site_name: PyETR

nav:
  - 'Home': 'index.md'
  - 'Getting started':
    - 'Installation': 'getting_started/installation.md'
    - 'Example': 'getting_started/example.md'
    - 'Case Example': 'getting_started/case_example.md'
  - 'Troubleshooting': 'troubleshooting.md'
  - 'Reference':
    - 'Case Index': 'case_index.md'
  - 'For Developers': 'development.md'
theme:
  name: 'material'
  palette:
    - scheme: default
      primary: 'green'
      accent: 'green'
      toggle:
          icon: material/lightbulb
          name: Switch to dark mode
    - scheme: slate
      primary: 'green'
      accent: 'light green'
      toggle:
          icon: material/lightbulb-outline
          name: Switch to light mode
  icon:
    logo: fontawesome/solid/brain


plugins:
  - search:
      separator: '[\s\-\.\_]+'