site_name: PyETR

nav:
  - 'Home': 'index.md'
  - 'Theory' :
    - 'Overview' : 'theory/overview.md'
    - 'Systems from R&I' : 'theory/systems.md'
  - 'Getting started': 
    - 'Installation': 'getting_started/installation.md'
    - 'Python': 'getting_started/getting_started_with_python.md'
  - 'Usage':
    - 'First Steps': 'getting_started/example.md'
    - 'Pre-defined Cases': 'getting_started/case_example.md'
    - 'View Construction': 'getting_started/view_construction.md'
    - 'View Methods Example': 'getting_started/view_methods_example.md'
    - 'Direct Decision Example': 'getting_started/direct_decision_example.md'
  - 'Advanced Usage':
    - 'Defining Inference': 'defining_inference.md'
    - 'Func Callers': 'func_callers.md'
    - 'Troubleshooting': 'troubleshooting.md'
    - 'Equality': 'view_equality_and_equivalence.md'
  - 'Reference':
    - 'Case Index': 'case_index.md'
    - 'View Methods': 'view_methods.md'
    - 'Inference Index': 'inference_index.md'
  - 'Glossary' : 'glossary.md'
  - 'For Developers': 'development.md'
  - 'Credits': 'credits.md'
theme:
  name: 'material'
  features:
    - content.code.copy
  palette:
    - scheme: default
      primary: 'black'
      accent: 'amber'
      toggle:
          icon: material/lightbulb
          name: Switch to dark mode
    - scheme: slate
      primary: 'yellow'
      accent: 'amber'
      toggle:
          icon: material/lightbulb-outline
          name: Switch to light mode
  icon:
    logo: fontawesome/solid/brain

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - toc:
      permalink: true
  - attr_list
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search:
      separator: '[\s\-\.\_]+'